import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/widgets/header";
import '../shared/styles/index.scss'
import { Footer } from "@/widgets/footer";

const geistInter = Inter({
  variable: "--font-geist-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "cyber",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistInter.variable} antialiased`}>
        <div className='wrapper'>
          <Header/>
          <main>
            {children}  
          </main>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
