import type { Metadata } from "next";
import { Cascadia_Code } from "next/font/google";

const geistCascadiaCode = Cascadia_Code({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "cyber",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistCascadiaCode.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
